module.exports = {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: true,
  quoteProps: 'as-needed',
  jsxSingleQuote: true,
  bracketSpacing: false,
  jsxBracketSameLine: false,
  trailingComma: 'all',
  arrowParens: 'avoid',
  requirePragma: false,
  endOfLine: 'lf',
}
